### ISSUE TITLE
Add new knives from new CSGO update

### ISSUE THREAD

**Issue by All-github-usernames-taken** [grayk79/knifechoose.nut#3]
In ur own time

Cheers

**Comment by p410n3** [comment]
Done :)

**Comment by All-github-usernames-taken** [comment]
F*CKING HELL, THAT WAS FAST. U literal god!!!!

**Comment by p410n3** [comment]
No problem

**Comment by SleeplessSloth** [comment]
By the way, my old phone broke and I lost the ability to log into my old account(yeah-yeah, I should've saved the backup codes somewhere but I guess I lost them as well since I couldn't find them anywhere at all). That's my new account now and I would be very thankful if you moved the repo to either your or my account and edit the README to point there. I can write you through steam to prove that I'm the original maintainer of the script, you've added me back then :) Thanks!

**Comment by All-github-usernames-taken** [comment]
Hi, I'm confused. Not sure if your talking to me, and I'm a noob at GitHub so I don't know if I can / how to move permissions...  Also not sure if you are grayk79 / PD Gray on gamebanana

**Comment by SleeplessSloth** [comment]
Yeah, that's me and my old nickname. Didn't want to confuse you, I just didn't think of a better place to write to Palone, sorry!

To be honest, I completely forgot about gamebanana, I'll (probably) update it soon. I'm also thinking of redoing the video since now I have an a lot more powerful PC and I'm able to add some text explaining and just a better viewer experience overall.

**Comment by p410n3** [comment]
1.) I will move a new fork to my account and add u ofc.

2) I don't care who makes a video, I don't need any edits i can't make myself, I'll just do it tomorrow

3) I don't care about you Pirating stuff, neither do I want to hear about it. Please leave that to relevant forums.

**Comment by All-github-usernames-taken** [comment]
alright my nigga, that's calm g
